DB_NAME = "bank.db"
CREATE_TABLES = "sql_CREATE_tables.sql"
DROP_DATABASE = "sql_DROP_DB.sql"

# DB_SQL_STRUCTURE = "sql_structure_file.sql"

BLOCK_AFTER_N_FAILED_ATTEMPTS = 5
BLOCK_FOR_N_MINUTES = 1

PASSWORD_MIN_LENGTH = 8
